#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Annotate PanTCR inferred alleles with retained-evidence and imputed regions.

This reporting-layer utility does not change genotype calls. It reads a PanTCR
inference CSV and the corresponding coordinate-projected observation CSV
generated by `collect_mutation.py`. For each inferred allele sequence, it reports
which mature-region coordinates were covered by retained sample-level evidence
after the same naive-diversity filtering used during inference, and which
coordinates were completed without retained evidence.

Coordinates in the output are 0-based and end-exclusive for intervals, matching
the internal PanTCR coordinate convention and mutation-token format.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import pandas as pd


Interval = Tuple[int, int]


def clean_text(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, float) and math.isnan(value):
        return ""
    return str(value).strip()


def clean_seq(value: object) -> str:
    return clean_text(value).upper().replace(" ", "")


def parse_ranges_part(text: object) -> List[Interval]:
    value = clean_text(text)
    if not value:
        return []
    out: List[Interval] = []
    for part in value.split(";"):
        part = part.strip()
        if not part:
            continue
        try:
            a_text, b_text = part.split(",", 1)
            a = int(a_text)
            b = int(b_text)
        except ValueError:
            continue
        if b < a:
            a, b = b, a
        out.append((a, b))
    return out


def parse_observed_ranges(text: object) -> List[Interval]:
    intervals: List[Interval] = []
    for piece in clean_text(text).split("|"):
        intervals.extend(parse_ranges_part(piece))
    return intervals


def split_to_float_list(value: object) -> List[Optional[float]]:
    out: List[Optional[float]] = []
    for part in split_pipe_list(value):
        if part == "":
            out.append(None)
            continue
        try:
            out.append(float(part))
        except ValueError:
            out.append(None)
    return out


def positions_to_ranges(positions: Iterable[int]) -> List[Interval]:
    vals = sorted(set(int(p) for p in positions))
    if not vals:
        return []
    ranges: List[Interval] = []
    start = prev = vals[0]
    for pos in vals[1:]:
        if pos == prev + 1:
            prev = pos
            continue
        ranges.append((start, prev + 1))
        start = prev = pos
    ranges.append((start, prev + 1))
    return ranges


def format_ranges(ranges: Sequence[Interval]) -> str:
    return ";".join(f"{a}-{b}" if b != a + 1 else str(a) for a, b in ranges)


def split_pipe_list(value: object) -> List[str]:
    text = clean_text(value)
    if not text:
        return []
    return [part.strip() for part in text.split("|")]


def retained_split_ranges(row: object, min_naive: Optional[float]) -> List[Interval]:
    """Return observed ranges that contribute nonzero evidence during inference."""
    obs_parts = split_pipe_list(getattr(row, "ObservedRanges", ""))
    if not obs_parts:
        return []

    div_parts = split_to_float_list(getattr(row, "DiversityIndexSplit", "")) if hasattr(row, "DiversityIndexSplit") else []
    naive_parts = split_to_float_list(getattr(row, "NaiveDiversityIndexSplit", "")) if hasattr(row, "NaiveDiversityIndexSplit") else []
    mlen = max(len(obs_parts), len(div_parts), len(naive_parts))
    obs_parts += [""] * (mlen - len(obs_parts))
    div_parts += [None] * (mlen - len(div_parts))
    naive_parts += [None] * (mlen - len(naive_parts))

    retained: List[Interval] = []
    for obs_text, div_value, naive_value in zip(obs_parts, div_parts, naive_parts):
        naive = 0.0 if naive_value is None else float(naive_value)
        if min_naive is not None and naive < float(min_naive):
            continue
        div = 0.0 if div_value is None else float(div_value)
        weight = max(0.0, div + 2.0 * naive)
        if weight <= 0:
            continue
        retained.extend(parse_ranges_part(obs_text))
    return retained


def load_default_reference(path: Path) -> Dict[str, str]:
    df = pd.read_csv(path)
    lower = {c.lower(): c for c in df.columns}
    gene_col = lower.get("gene") or lower.get("family")
    seq_col = lower.get("sequence") or lower.get("seq")
    if gene_col is None or seq_col is None:
        raise ValueError(f"Reference CSV must contain Gene/Family and Sequence columns: {path}")
    refs: Dict[str, str] = {}
    for row in df.itertuples(index=False):
        gene = clean_text(getattr(row, gene_col))
        seq = clean_seq(getattr(row, seq_col))
        if gene and seq:
            refs[gene] = seq
    return refs


def retained_evidence_by_gene(sample_csv: Path, min_naive: Optional[float]) -> Tuple[Dict[str, Set[int]], Dict[str, Dict[int, Set[str]]]]:
    df = pd.read_csv(sample_csv)
    required = {"Family", "ObservedRanges", "Sequence"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Observation CSV missing required columns {sorted(missing)}: {sample_csv}")
    if min_naive is not None:
        if "NaiveDiversityIndex" not in df.columns:
            raise ValueError(f"Observation CSV lacks NaiveDiversityIndex for --min-naive filtering: {sample_csv}")
        naive = pd.to_numeric(df["NaiveDiversityIndex"], errors="coerce").fillna(0)
        df = df[naive >= float(min_naive)].copy()

    covered: Dict[str, Set[int]] = {}
    bases: Dict[str, Dict[int, Set[str]]] = {}
    for row in df.itertuples(index=False):
        gene = clean_text(getattr(row, "Family", ""))
        seq = clean_seq(getattr(row, "Sequence", ""))
        if not gene or not seq:
            continue
        gene_cov = covered.setdefault(gene, set())
        gene_bases = bases.setdefault(gene, {})
        for a, b in retained_split_ranges(row, min_naive=min_naive):
            for pos in range(a, b):
                gene_cov.add(pos)
                if 0 <= pos < len(seq):
                    gene_bases.setdefault(pos, set()).add(seq[pos])
    return covered, bases


def mutation_token(ref_base: str, pos: int, alt_base: str) -> str:
    return f"S{ref_base}{pos}{alt_base}"


def default_relative_changes(seq: str, ref: str) -> List[Tuple[int, str, str, str]]:
    n = min(len(seq), len(ref))
    out: List[Tuple[int, str, str, str]] = []
    for pos in range(n):
        ref_base = ref[pos].upper()
        alt_base = seq[pos].upper()
        if ref_base != alt_base:
            out.append((pos, ref_base, alt_base, mutation_token(ref_base, pos, alt_base)))
    return out


def support_class_for_change(pos: int, alt_base: str, observed_bases: Dict[int, Set[str]]) -> str:
    bases = {b.upper() for b in observed_bases.get(pos, set()) if b}
    if not bases:
        return "graph_imputed"
    has_alt = alt_base.upper() in bases
    has_conflict = any(base != alt_base.upper() for base in bases)
    if has_alt and not has_conflict:
        return "evidence_supported"
    if has_alt and has_conflict:
        return "evidence_supported_with_conflict"
    return "covered_but_not_supporting"


def infer_allele_slots(row: pd.Series) -> List[Tuple[str, str, str]]:
    slots: List[Tuple[str, str, str]] = []
    for slot in ["A", "B", "C", "D"]:
        allele_col = f"allele_{slot}"
        seq_col = f"seq_{slot}"
        if allele_col not in row.index or seq_col not in row.index:
            continue
        allele = clean_text(row.get(allele_col, ""))
        seq = clean_seq(row.get(seq_col, ""))
        if allele and seq:
            slots.append((slot, allele, seq))
    return slots


def audit(infer_csv: Path, sample_csv: Path, reference_csv: Path, out_prefix: Path, min_naive: Optional[float]) -> None:
    infer_df = pd.read_csv(infer_csv)
    if "gene" not in infer_df.columns:
        raise ValueError(f"Inference CSV must contain a gene column: {infer_csv}")
    refs = load_default_reference(reference_csv)
    covered_by_gene, bases_by_gene = retained_evidence_by_gene(sample_csv, min_naive=min_naive)

    summary_rows: List[dict] = []
    site_rows: List[dict] = []

    for _, row in infer_df.iterrows():
        gene = clean_text(row.get("gene", ""))
        if not gene:
            continue
        ref = refs.get(gene, "")
        for slot, allele, seq in infer_allele_slots(row):
            length = len(seq)
            retained_positions = {p for p in covered_by_gene.get(gene, set()) if 0 <= p < length}
            imputed_positions = set(range(length)) - retained_positions
            observed_bases = bases_by_gene.get(gene, {})
            changes = default_relative_changes(seq, ref) if ref else []

            by_class: Dict[str, List[str]] = {
                "evidence_supported": [],
                "evidence_supported_with_conflict": [],
                "graph_imputed": [],
                "covered_but_not_supporting": [],
            }
            for pos, ref_base, alt_base, token in changes:
                cls = support_class_for_change(pos, alt_base, observed_bases)
                by_class.setdefault(cls, []).append(token)
                site_rows.append({
                    "gene": gene,
                    "allele_slot": slot,
                    "allele_name": allele,
                    "position_0based": pos,
                    "reference_base": ref_base,
                    "inferred_base": alt_base,
                    "default_relative_change": token,
                    "support_class": cls,
                    "retained_observed_bases": "|".join(sorted(observed_bases.get(pos, set()))),
                    "min_naive_filter": "" if min_naive is None else min_naive,
                })

            summary_rows.append({
                "gene": gene,
                "allele_slot": slot,
                "allele_name": allele,
                "sequence_length": length,
                "retained_evidence_covered_position_count": len(retained_positions),
                "graph_imputed_position_count": len(imputed_positions),
                "retained_evidence_covered_ranges_0based": format_ranges(positions_to_ranges(retained_positions)),
                "graph_imputed_ranges_0based": format_ranges(positions_to_ranges(imputed_positions)),
                "default_relative_change": ";".join(token for _, _, _, token in changes),
                "evidence_supported_change": ";".join(by_class.get("evidence_supported", [])),
                "evidence_supported_with_conflict_change": ";".join(by_class.get("evidence_supported_with_conflict", [])),
                "graph_imputed_change": ";".join(by_class.get("graph_imputed", [])),
                "covered_but_not_supporting_change": ";".join(by_class.get("covered_but_not_supporting", [])),
                "min_naive_filter": "" if min_naive is None else min_naive,
            })

    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(summary_rows).to_csv(Path(str(out_prefix) + ".summary.csv"), index=False)
    pd.DataFrame(site_rows).to_csv(Path(str(out_prefix) + ".site_detail.csv"), index=False)


def main() -> None:
    ap = argparse.ArgumentParser(description="Annotate PanTCR inferred allele sequences by retained evidence and graph-imputed regions.")
    ap.add_argument("--infer-csv", required=True, type=Path, help="PanTCR inference CSV.")
    ap.add_argument("--sample-csv", required=True, type=Path, help="Coordinate-projected observation CSV generated by collect_mutation.py.")
    ap.add_argument("--reference-csv", required=True, type=Path, help="Gene-specific default/reference sequence CSV, e.g. IMGT_TRB_default.csv.")
    ap.add_argument("--out-prefix", required=True, type=Path, help="Output prefix. Writes .summary.csv and .site_detail.csv.")
    ap.add_argument("--min-naive", type=float, default=2, help="NaiveDiversityIndex threshold used to define retained sample-level evidence.")
    args = ap.parse_args()
    audit(args.infer_csv, args.sample_csv, args.reference_csv, args.out_prefix, args.min_naive)


if __name__ == "__main__":
    main()
